// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvozpnlcteumpagepstb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2b3pwbmxjdGV1bXBhZ2Vwc3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjA2MjcsImV4cCI6MjA2ODg5NjYyN30.dd3De4S4MBSPidvrTdpPOUFBT2G2XDqg522rY5mmITc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});